# Generated by Django 5.2.3 on 2025-10-05 17:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0011_alter_recipe_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="image",
            field=models.ImageField(
                blank=True,
                default="recipes/default.jpg",
                null=True,
                upload_to="recipes/",
            ),
        ),
    ]
