# Generated by Django 5.2.3 on 2025-12-26 04:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0012_alter_recipe_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="recipes/"),
        ),
    ]
